language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -r ./requirements.txt

script:
  # - cd test_scripts
  # - python test_img2xml.py
  # - python test_mask2json.py
  # - python test_multiObjs2Xml.py
  # - python test_json2xml.py
  # - python test_xml2yolo.py
  # - python test_generateMask.py
  # - python test_list2yaml.py
  # - python test_xml2json.py
  # - python test_img2b64.py
  - cd /home/travis/build/guchengxi1994/mask2json/convertmask
  - python main_v_0_5_any.py mask2json /home/travis/build/guchengxi1994/mask2json/static/multi_objs.jpg  /home/travis/build/guchengxi1994/mask2json/multi_objs_json/label.png  /home/travis/build/guchengxi1994/mask2json/multi_objs_json/info.yaml

notifications:
  on_success: always
cache: pip